version: "3.9"
services:
  amrum-be:
    build: .
    container_name: amrum-be
    ports:
      - "8123:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=${ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_SENDER_EMAIL=${EMAIL_SENDER_EMAIL}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SEND_REAL_EMAILS=${SEND_REAL_EMAILS:-true}
    external_links:
      - postgres:postgres
    restart: unless-stopped
