"""extended booking model

Revision ID: fbc92e7d9442
Revises: c69212971a9a
Create Date: 2025-03-12 16:17:23.024409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc92e7d9442'
down_revision: Union[str, None] = 'c69212971a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('final_info_sent', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('invoice_created', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('invoice_sent', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'modified_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'paid')
    op.drop_column('bookings', 'invoice_sent')
    op.drop_column('bookings', 'invoice_created')
    op.drop_column('bookings', 'final_info_sent')
    op.drop_column('bookings', 'confirmed')
    # ### end Alembic commands ###
